version: '3'

services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: invstore
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - invstore-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  invstore:
    image: invstore/invstore:latest
    container_name: invstore-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: invstore
      MYSQL_USERNAME: your_mysql_user
      MYSQL_PASSWORD: password
      JWT_SECRET: crazylongjwtsecretnobodywilleverguessinamillionyears
    networks:
      - invstore-net

networks:
  invstore-net: