spring:
  application:
    name: invstore-jvm
  datasource:
    url: jdbc:mysql://localhost:3306/invstore?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 8b48f13c7553a3204524
            client-secret: d132cccdfbe7d5ad365de1adae9838912d1fea63

logging:
  level:
    org:
      springframework:
        security: DEBUG

springdoc:
  swagger-ui:
    csrf:
      enabled: true

# App Properties
invstore:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000