export const StoreState = {
  hideConfigButton: 'hideConfigButton',
  isPinned: 'isPinned',
  showConfig: 'showConfig',
  sidebarType: 'sidebarType',
  isRTL: 'isRTL',
  mcolor: 'mcolor',
  darkMode: 'darkMode',
  isNavFixed: 'isNavFixed',
  isAbsolute: 'isAbsolute',
  showNavs: 'showNavs',
  showSidenav: 'showSidenav',
  showNavbar: 'showNavbar',
  showFooter: 'showFooter',
  showMain: 'showMain',
  layout: 'layout',
};

export default {
    hideConfigButton: false,
    isPinned: false,
    showConfig: false,
    sidebarType: "bg-white",
    isRTL: false,
    mcolor: "",
    darkMode: false,
    isNavFixed: false,
    isAbsolute: false,
    showNavs: true,
    showSidenav: true,
    showNavbar: true,
    showFooter: true,
    showMain: true,
    layout: "default",
};
